test build docs

diff --git a/tools/pipelines/test-azure-frs.yml b/tools/pipelines/test-azure-frs.yml
--- a/tools/pipelines/test-azure-frs.yml
+++ b/tools/pipelines/test-azure-frs.yml
@@ -249,21 +249,30 @@ stages:
             workingDirectory: $(Build.SourcesDirectory)
             script: |
               output=$(node docs/readJSON.js)
-              # Loop through each value in the array
-              echo "$output" | while IFS= read -r version; do
-                version=$(echo "$version" | sed 's/"//g')
-                echo "Version: $version"
 
-                echo "creating api-extractor-temp-$version folder"
-                mkdir -p $(Build.SourcesDirectory)/_api-extractor-temp-$version/doc-models
+              if [ $? -ne 0 ]; then
+                echo "Node.js script failed with an error:"
+                echo "$output"  # Output any errors to investigate script failure
+              else
+                echo "Node.js script executed successfully."
+                echo "$output" 
 
-                az storage blob download -f latest-$version.tar.gz -c 'api-extractor-json' -n latest-$version.tar.gz --account-name $(STORAGE_ACCOUNT) --account-key $(STORAGE_KEY) --overwrite --verbose
+                # Loop through each value in the array
+                echo "$output" | while IFS= read -r version; do
+                  version=$(echo "$version" | sed 's/"//g')
+                  echo "Version: $version"
 
-                ls -l
-                
-                tar -xzf latest-$version.tar.gz -C _api-extractor-temp-$version/doc-models
+                  echo "creating api-extractor-temp-$version folder"
+                  mkdir -p $(Build.SourcesDirectory)/_api-extractor-temp-$version/doc-models
 
-              done <<< "$json_content"
+                  az storage blob download -f latest-$version.tar.gz -c 'api-extractor-json' -n latest-$version.tar.gz --account-name $(STORAGE_ACCOUNT) --account-key $(STORAGE_KEY) --overwrite --verbose
+
+                  ls -l
+                  
+                  tar -xzf latest-$version.tar.gz -C _api-extractor-temp-$version/doc-models
+
+                done
+              fi
 
         - task: Npm@1
           # displayName: npm run build
